### ISSUE TITLE
Running the examples in Windows returns an "Invalid Signature" error

### ISSUE THREAD

**Issue by ianmcdaniel** [TeleSign/node_telesign#1]
The problem appears to be in the authorization signature code 
````javascript
var stringToSignBuilder = methodName +
os.EOL + contentType +
os.EOL + date +
os.EOL + "x-ts-auth-method:" + authMethod +
os.EOL + "x-ts-nonce:" + nonce +
urlencoded +
os.EOL + resource;
````

`os.EOL` returns `/r/n` in Windows but it seems that telesign expects `/n`

**Comment by jarradsl** [comment]
Hi @ianmcdaniel, thanks for reporting this! We will have a fix for the issue shortly.

**Comment by peacepirate** [comment]
@ianmcdaniel Please test using the latest master updates.

**Comment by peacepirate** [comment]
Assuming the silence to mean good times with the SDK, closing the issue.
